[project]
name = "oaqjp-final-project-emb-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "ibm-watson>=9.0.0",
    "nltk>=3.9.1",
    "pylint>=3.3.6",
    "requests>=2.32.3",
]
